#!/bin/bash

# macports
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# why does port select not do this, ugh
export PATH="/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH"
export PATH="/Users/julian/Library/Python/3.6/bin:$PATH"
export PATH="/Applications/racket/bin:$PATH"

export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="$HOME/.dotfiles/local/bin:$PATH"
export PATH="$HOME/.dotfiles/local/miniconda3/bin:$PATH"

# export PYTHONPATH="/Users/julian/Library/Python/2.7/lib/python/site-packages"

export CLASSPATH="/usr/local/lib:/usr/local/lib/antlr-4.7-complete.jar:$CLASSPATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/julian/Documents/git/dotfiles/local/google-cloud-sdk/path.bash.inc' ]; then source '/Users/julian/Documents/git/dotfiles/local/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/julian/Documents/git/dotfiles/local/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/julian/Documents/git/dotfiles/local/google-cloud-sdk/completion.bash.inc'; fi
